[package]
name = "chess-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
chess = { git = "https://github.com/INDA23PlusPlus/simonsev-chess" }
ggez = "0.9.3"
lazy_static = "1.4.0"
log = "0.4.20"
